spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://baidu.com
          predicates:
            - Query=url,baidu
        - id: test_route1
          uri: https://qq.com
          predicates:
            - Query=url,qq



