server:
  port: 8006

alibaba:
  cloud:
    access-key: LTAI5tNG4WQHxyhSRTENpzgZ
    secret-key: T4EweDGAt64GHUrimyQ6ifvd2bNVUj
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      bucket: ggulimall-lt

spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
