server:
  port: 8006



spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848

    sms:
      appcode: 61ad6350e48146828c977afb5c5fc813
