server:
  port: 8007


spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


  thymeleaf:
    cache: false



# 日志配置
logging:
  level:
    com.lt.gulimall: debug
    org.springframework: warn
